version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/WordPress
permissions:
  - object: /scripts 
    pattern: "**" 
    owner: ec2-user 
    mode: 777 
    type: 
      - file 
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
