version: 0.0
os: linux
# a sample change 
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
   - location: scripts/deregister_from_elb
     runas: root
  ApplicationStart:
   - location: scripts/register_with_elb
     runas: root
